module.exports={  rgyud_om: '1' ,
  rgyud_ka: 2,
  rgyud_kha: 3,
  rgyud_ga: 4,
  rgyud_nga: 5,
  rgyud_ca: 6,
  rgyud_cha: 7,
  rgyud_ja: 8,
  rgyud_nya: 9,
  rgyud_ta: 10,
  rgyud_tha: 11,
  rgyud_da: 12,
  rgyud_na: 13,
  rgyud_pa: 14,
  rgyud_pha: 15,
  rgyud_ba: 16,
  rgyud_ma: 17,
  rgyud_tsa: 18,
  rgyud_tsha: 19,
  rgyud_dza: 20,
  rgyud_wa: 21,
  rgyud_zha: 22,
  rgyud_za: 23,
 "rgyud_'a": 24,
  rgyud_ya: 25,
 'sher phyin_ra': 26,
  'sher phyin_la': 27,
  'sher phyin_sha': 28,
  'sher phyin_sa': 29,
  'sher phyin_ha': 30,
  'sher phyin_aa': 31,
  'sher phyin_KSHa': 32,
  'sher phyin_ki': 33,
  'sher phyin_khi': 34,
  'sher phyin_gi': 35,
  'sher phyin_ngi': 36,
  'sher phyin_ci': 37,
  'sher phyin_chi': 38,
  'sher phyin_ji': 39,
  'sher phyin_nyi': 40,
  'sher phyin_ti': 41,
  'sher phyin_thi': 42,
  'sher phyin_di': 43,
  'sher phyin_ni': 44,
  'sher phyin_pi': 45,
  'sher phyin_phi': 46,
  'sher phyin_bi': 47,
  'sher phyin_mi': 48,
  'sher phyin_tsi': 49,
  'dkonbrtsegs_tshi': 50,
  'dkonbrtsegs_dzi': 51,
  'dkonbrtsegs_wi': 52,
   'dkonbrtsegs_zhi': 53,
  'dkonbrtsegs_zi': 54,
 'dkonbrtsegs_\'i': 55,
 'phal chen_yi': 56,
 'phal chen_ri': 57,
 'phal chen_li': 58,
 'phal chen_shi': 59,
 'phal chen_si': 60,
 'phal chen_hi': 61,
  'mdo_ai': 62,
  'mdo sna tshogs_ku': 63,
  'mdo sna tshogs_khu': 64,
  'mdo sna tshogs_gu': 65,
  'mdo sna tshogs_ngu': 66,
  'mdo sna tshogs_cu': 67,
  'mdo sna tshogs_chu': 68,
  'mdo sna tshogs_ju': 69,
  'mdo sna tshogs_nyu': 70,
  'mdo sna tshogs_tu': 71,
  'mdo sna tshogs_thu': 72,
  'mdo sna tshogs_du': 73,
  'mdo sna tshogs_nu': 74,
  'mdo sna tshogs_pu': 75,
  'mdo sna tshogs_phu': 76,
  'mdo sna tshogs_bu': 77,
  'mdo sna tshogs_mu': 78,
  'mdo sna tshogs_tsu': 79,
  'mdo sna tshogs_tshu': 80,
  'mdo sna tshogs_dzu': 81,
  'mdo sna tshogs_wu': 82,
  'mdo sna tshogs_zhu': 83,
  'mdo sna tshogs_zu': 84,
  'mdo sna tshogs_\'u': 85,
  'mdo sna tshogs_yu': 86,
  'mdo sna tshogs_ru': 87,
  'mdo sna tshogs_lu': 88,
  'mdo sna tshogs_shu': 89,
  'mdo sna tshogs_su': 90,
  'mdo sna tshogs_hu': 91,
  'mdo sna tshogs_au': 92,
  'mdo sna tshogs_ke': 93,
 '\'dulba_khe': 94,
 '\'dulba_ge': 95,
 '\'dulba_nge': 96,
  '\'dulba_ce': 97,
  '\'dulba_che': 98,
  '\'dulba_je': 99,
  '\'dulba_nye': 100,
  '\'dulba_te': 101,
  '\'dulba_the': 102,
  '\'dulba_de': 103,
  '\'dulba_ne': 104,
  '\'dulba_pe': 105,
  '\'dulba_phe': 106}